[package]
name = "rust-dietician"
version = "0.1.0"
authors = ["Simon Heath <icefoxen@gmail.com>"]

[dependencies]

elf = { git = "https://github.com/cole14/rust-elf.git" }
clap = "2"
rustc-demangle = "0.1"
